obj-m = device_drive.o

all:
				make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
				make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

test:test.c
				gcc -o test test.c
